"""Bundled example catalogue - the current input source.

Applications resolve demo inputs through this module using logical example IDs,
so they never need to know how a dataset is organised on disk. A future imagery
provider (location + date -> image pair) will occupy exactly this role; only the
resolver changes, not the applications.

The catalogue itself is examples/catalogue.json, generated by
scripts/build_example_catalogue.py. It records only facts that exist: file
paths, whether a ground-truth mask is available, and the measured ground-truth
change fraction. No location or acquisition-date metadata is recorded, because
none is available for this imagery.
"""
from __future__ import annotations

import json
import os
from dataclasses import dataclass
from typing import Optional

from src import config


@dataclass(frozen=True)
class Example:
    """One selectable input pair."""
    id: str
    name: str
    domain: str
    before: str                      # repo-relative path
    after: str                       # repo-relative path
    ground_truth: Optional[str] = None
    description: str = ""
    source: str = ""

    # --- resolved absolute paths ---
    @property
    def before_path(self) -> str:
        return config.resolve(self.before)

    @property
    def after_path(self) -> str:
        return config.resolve(self.after)

    @property
    def ground_truth_path(self) -> Optional[str]:
        return config.resolve(self.ground_truth) if self.ground_truth else None

    @property
    def has_ground_truth(self) -> bool:
        p = self.ground_truth_path
        return bool(p) and os.path.exists(p)

    def exists(self) -> bool:
        """True when both images are actually present on this machine."""
        return os.path.exists(self.before_path) and os.path.exists(self.after_path)

    def to_dict(self) -> dict:
        return {"id": self.id, "name": self.name, "domain": self.domain,
                "before": self.before, "after": self.after,
                "ground_truth": self.ground_truth,
                "description": self.description, "source": self.source}


def load_catalogue(path: Optional[str] = None) -> list:
    """All catalogue entries, present on disk or not."""
    path = path or config.EXAMPLES_CATALOGUE
    if not os.path.exists(path):
        return []
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    return [Example(**e) for e in data.get("examples", [])]


def available(domain: Optional[str] = None, path: Optional[str] = None) -> list:
    """Entries whose image files exist here, optionally filtered by domain.

    The dataset-derived examples only exist once the dataset has been prepared,
    so an application must tolerate an empty or partial catalogue.
    """
    items = [e for e in load_catalogue(path) if e.exists()]
    if domain:
        items = [e for e in items if e.domain == domain]
    return items


def get(example_id: str, path: Optional[str] = None) -> Example:
    for e in load_catalogue(path):
        if e.id == example_id:
            return e
    raise KeyError(f"unknown example id '{example_id}'")
